#!/bin/bash
echo "# aprsNetworkStart starting" > /tmp/anc.txt
date >> /tmp/anc.txt

modprobe i2c_bcm2708
modprobe i2c_dev

echo "# dmesg after modprobe" >> /tmp/anc.txt
dmesg >> /tmp/anc.txt
echo "" >> /tmp/anc.txt

echo "# lsmod after modprobe" >> /tmp/anc.txt
lsmod >> /tmp/anc.txt
echo "" >> /tmp/anc.txt

# echo "# i2cdetect -y 1" >> /tmp/anc.txt
# i2cdetect -y 1 >> /tmp/anc.txt
# echo "" >> /tmp/anc.txt

echo "# ifconfig" >> /tmp/anc.txt
ifconfig >> /tmp/anc.txt
echo "" >> /tmp/anc.txt

# echo "# original /etc/network/interfaces" >> /tmp/anc.txt
# cat /etc/network/interfaces >> /tmp/anc.txt
# echo "" >> /tmp/anc.txt

# echo "# saving eeprom_2464 stderr to /tmp/anc.err" >> /tmp/anc.txt
# eeprom_2464 --read /dev/stdout --string --start-address 289 --n-bytes 479 >> /tmp/anc.txt 2>/tmp/anc.err

echo "# networkFromJSON proposed /etc/network/interfaces" >> /tmp/anc.txt
eeprom_2464 --read /dev/stdout --string --start-address 289 --n-bytes 479 2>/dev/null | /home/aprs/MagWebPro/networkFromJSON >> /tmp/anc.txt
echo "" >> /tmp/anc.txt

# write /tmp/anc.txt to EEPROM
#eeprom_2464 --write /tmp/anc.txt --string --start-address 1024
