#!/bin/bash

function lcd_prompt {
		echo "[LCD PROMPT] " "$1"
		python /home/aprs/tinyFrontPanelLcd/tinyLCDimage.py "$1" /home/aprs/tinyFrontPanelLcd/res/images/logo2.ppm
}

function button_prompt_wait {
	# prompt operator to press the button 
	lcd_prompt "$2"
	
	# wait for button press
	while : ; do
		read -r BUTTON < /sys/class/gpio/gpio$1/value
	
		if [ "$BUTTON" == "1" ]
		then
			break
		fi

		sleep 0.1
	done
}

function barcode_scanner_prompt_wait {
	# if device doesn't exist, prompt user to plugin and wait until it does exist
	if [ ! -e $1 ]; then
		lcd_prompt "Plug in USB barcode scanner"

		# wait until device file exists
		while [ ! -e $1 ]; do
			sleep 0.1
		done

		sleep 1
	fi

	# prompt operator to scan pcb bar code 
	lcd_prompt "Scan PCB barcode" 
	
	# wait for button press
	read -r BARCODE < $1

	button_prompt_wait 27 "SN=$BARCODE OK? MIDDLE"

	# set hostname
	sethostname $BARCODE
}

# Export button GPIOs if they aren't already
if [ ! -e /sys/class/gpio/gpio17/direction ]; then
	echo "# exporting GPIO17 for sysfs control"
	echo 17 > /sys/class/gpio/export
fi

if [ ! -e /sys/class/gpio/gpio27/direction ]; then
	echo "# exporting GPIO27 for sysfs control"
	echo 27 > /sys/class/gpio/export
fi

if [ ! -e /sys/class/gpio/gpio18/direction ]; then
	echo "# exporting GPIO18 for sysfs control"
	echo 18 > /sys/class/gpio/export
fi

# wait for export to happen and direction permissions to be set
sleep 0.1

lcd_prompt "Initial test"

# set direction to input
echo in > /sys/class/gpio/gpio17/direction
echo in > /sys/class/gpio/gpio27/direction
echo in > /sys/class/gpio/gpio18/direction

# test RTC by attempting read. Will return 0 if good
rtc_ds1307 --i2c-address 0x68 --read 
if [[ $? -ne 0 ]]; then
	lcd_prompt "RTC faulty!"
	exit 1
else
	lcd_prompt "RTC passed"
fi

# test EEPROM by attempting read. Will return 0 if good
eeprom_2464 --i2c-address 0x68 --n-bytes 1 --read /dev/null
if [[ $? -ne 0 ]]; then
	lcd_prompt "EEPROM faulty!"
	exit 1
else
	lcd_prompt "EEPROM passed"
fi

# test buttons
button_prompt_wait 18 "Press LEFT button"
button_prompt_wait 27 "Press MIDDLE button"
button_prompt_wait 17 "Press RIGHT button"

# switch to rw so we can set hostname
root-rw

# use USB barcode scanner to set hostname
barcode_scanner_prompt_wait /dev/ttyACM0



# release the button GPIOs from sysfs
echo 17 > /sys/class/gpio/unexport
echo 18 > /sys/class/gpio/unexport
echo 27 > /sys/class/gpio/unexport


lcd_prompt "printing label"
read -r HOSTNAME < /etc/hostname
MAC=`ifconfig | grep eth0 | cut -c39-55`
URL="http://192.168.10.188/registration/mwp.php?mac=$MAC&hostname=$HOSTNAME"
curl "$URL"



lcd_prompt "`hostname` shutting down"

root-ro

# do shutdown
#halt
